export const CHAIN_ID = {
  MAINNET: '0x2b6653dc',
  SHASTA: '0x94a9059e',
  NILE: '0xcd8690dc',
} as const;

export enum TokenType {
  TRX = 0,
  TRC10 = 1,
  TRC20 = 2,
  TRC721 = 5,
}

export enum ContractType {
  AccountCreateContract = 0,
  TransferContract = 1,
  TransferAssetContract = 2,
  VoteAssetContract = 3,
  VoteWitnessContract = 4,
  WitnessCreateContract = 5,
  AssetIssueContract = 6,
  WitnessUpdateContract = 8,
  ParticipateAssetIssueContract = 9,
  AccountUpdateContract = 10,
  FreezeBalanceContract = 11,
  UnfreezeBalanceContract = 12,
  WithdrawBalanceContract = 13,
  UnfreezeAssetContract = 14,
  UpdateAssetContract = 15,
  ProposalCreateContract = 16,
  ProposalApproveContract = 17,
  ProposalDeleteContract = 18,
  SetAccountIdContract = 19,
  CustomContract = 20,
  CreateSmartContract = 30,
  TriggerSmartContract = 31,
  GetContract = 32,
  UpdateSettingContract = 33,
  ExchangeCreateContract = 41,
  ExchangeInjectContract = 42,
  ExchangeWithdrawContract = 43,
  ExchangeTransactionContract = 44,
  UpdateEnergyLimitContract = 45,
  AccountPermissionUpdateContract = 46,
  ClearABIContract = 48,
  UpdateBrokerageContract = 49,
  ShieldedTransferContract = 51,
  MarketSellAssetContract = 52,
  MarketCancelOrderContract = 53,
  FreezeBalanceV2Contract = 54,
  UnfreezeBalanceV2Contract = 55,
  WithdrawExpireUnfreezeContract = 56,
  DelegateResourceContract = 57,
  UnDelegateResourceContract = 58,
  CancelAllUnfreezeV2Contract = 59,
  FeeContract = 300,
  UnfreezeV2WithdrawContract = 400,
  CancelAllUnfreezeV2WithdrawContract = 500,
}

export const contractTypeNumMapString: Record<number, string> = {
  0: 'AccountCreateContract',
  1: 'TransferContract',
  2: 'TransferAssetContract',
  3: 'VoteAssetContract',
  4: 'VoteWitnessContract',
  5: 'WitnessCreateContract',
  6: 'AssetIssueContract',
  8: 'WitnessUpdateContract',
  9: 'ParticipateAssetIssueContract',
  10: 'AccountUpdateContract',
  11: 'FreezeBalanceContract',
  12: 'UnfreezeBalanceContract',
  13: 'WithdrawBalanceContract',
  14: 'UnfreezeAssetContract',
  15: 'UpdateAssetContract',
  16: 'ProposalCreateContract',
  17: 'ProposalApproveContract',
  18: 'ProposalDeleteContract',
  19: 'SetAccountIdContract',
  20: 'CustomContract',
  30: 'CreateSmartContract',
  31: 'TriggerSmartContract',
  32: 'GetContract',
  33: 'UpdateSettingContract',
  41: 'ExchangeCreateContract',
  42: 'ExchangeInjectContract',
  43: 'ExchangeWithdrawContract',
  44: 'ExchangeTransactionContract',
  45: 'UpdateEnergyLimitContract',
  46: 'AccountPermissionUpdateContract',
  48: 'ClearABIContract',
  49: 'UpdateBrokerageContract',
  51: 'ShieldedTransferContract',
  52: 'MarketSellAssetContract',
  53: 'MarketCancelOrderContract',
  54: 'FreezeBalanceV2Contract',
  55: 'UnfreezeBalanceV2Contract',
  56: 'WithdrawExpireUnfreezeContract',
  57: 'DelegateResourceContract',
  58: 'UnDelegateResourceContract',
  59: 'CancelAllUnfreezeV2Contract',
  300: 'FeeContract',
  400: 'UnfreezeV2WithdrawContract',
  500: 'CancelAllUnfreezeV2WithdrawContract',
};

export const USDTContractAddress: Record<string, string> = {
  mainnet: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
  shasta: 'TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs',
  nile: 'TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf',
};

export const MAINNET_CHAIN_ID = CHAIN_ID.MAINNET;
